#!/bin/bash

set -e

echo Building...

bundle exec jekyll build

git checkout master

shopt -s extglob
rm -rf !(_site)

cp -r _site/* .

git status

read -p "I will now add all changes, commit and push them. Shall I continue (y/n)?" CONT
if [ "$CONT" = "y" ]; then
  echo "on it...";
  git add .;
  read -p "please type commit message" commitmsg;
  git commit -m "$commitmsg"
  git push;
  echo "done"
else
  echo "Fine, do it yourself";
fi

